USE [master]
GO

/****** Object:  Database [DB_A1A940_philameter]    Script Date: 03/28/2017 12:01:06 
CREATE DATABASE [DB_A1A940_philameter] ON  PRIMARY 
( NAME = N'DB_A1A940_philameter', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DB_A1A940_philameter.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_A1A940_philameter_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\DB_A1A940_philameter_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO ******/

ALTER DATABASE [DB_A1A940_philameter] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_A1A940_philameter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_A1A940_philameter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DB_A1A940_philameter] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DB_A1A940_philameter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_A1A940_philameter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_A1A940_philameter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_A1A940_philameter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_A1A940_philameter] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DB_A1A940_philameter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_A1A940_philameter] SET  READ_WRITE 
GO

ALTER DATABASE [DB_A1A940_philameter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_A1A940_philameter] SET  MULTI_USER 
GO

ALTER DATABASE [DB_A1A940_philameter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_A1A940_philameter] SET DB_CHAINING OFF 
GO

